---
title: "KDX_Competition"
author: 개인팀(이현범)
output:
  html_document:
   toc: true
   toc_float:
     collapsed: true
     smooth_scroll: true
   theme: united
   highlight: textmate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE, message = FALSE)
```
### 1. 분석 준비

시각화 그래프에서 한글깨짐 현상으로 extrafont 패키지 설치  
install.packages("extrafont")

#### 1.1 패키지 준비 
```{r}
# 패키지 불러오기
library(ggplot2)
library(readxl)
library(lubridate)
library(dplyr)
library(tidyr)
library(stringr)
library(extrafont)
```
#### 1.2 데이터 불러오기
```{r}
card <- read_xlsx(path = "/home/kdx030/sample/Samsungcard.xlsx")
shin <- read_xlsx(path = "/home/kdx030/sample/Shinhancard.xlsx")

glimpse(card)
glimpse(shin)
```

#### 1.3 데이터 전처리
##### 1.3.1 삼성카드
```{r}
card <- card %>%
  separate(소비일자, into = c("year", "day"), sep = 4) # 날짜를 year과 day로 분할
card <- card %>%
  separate(day, into = c("month","day"), sep = 2) # day를 month와 day로 분할
card <- card %>%
  unite(소비일자, year, month, day, sep = "-") # year, month, day 소비일자 열에 - 추가한 뒤 붙여줌
card$소비일자 <- ymd(card$소비일자) # 소비일자 형식 date 타입으로 변경

names(card)[2] <- c("업종") # 열 이름 바꾸기

card$소비건수 <- card$소비건수 / 1000 # 삼성카드 소비건수 데이터값도 천원단위로 바꾸기

card
```

#### 1.3.2 신한카드
```{r}
shin <- shin %>%
  select(-...6,-...7,-...8) %>% # 결측값이 포함된 열 제거
  separate(일별, into = c("year", "day"), sep = 4) %>% # 날짜를 year과 day로 분할
  separate(day, into = c("month", "day"), sep = 2) %>% # day를 month와 day로 분할
  unite(소비일자, year, month, day, sep = "-") %>% # year, month, day 소비일자 열에 - 추가한 뒤 붙여줌
  mutate(성별 = str_replace(성별, "M", "남성")) %>% # 성별 M 에서 남성으로 변경
  mutate(성별 = str_replace(성별, "F", "여성")) %>% # 성별 F에서 여성으로 변경
  separate(업종, into = c("삭제","업종"), sep = 5) %>% # 업종 이름에서 Mxxx_ 없애기
  select(-삭제)

names(shin)[3] <- c("연령대") # 열 이름 바꾸기
names(shin)[5] <- c("소비건수")

shin <- shin[c(1,4,2,3,5)] # 열 순서 바꾸기

shin$소비일자 <- ymd(shin$소비일자) # 소비일자 형식 date 타입으로 변경
shin <- shin[!(shin$연령대 >= "70대"), ] # 연령대 열에서 70대 삭제 (삼성카드와 통일)

# 신한카드 기타요식, 일식/중식/양식, 한식, 제과/커피/패스트푸드, 유흥 하나로 합치기
shin <- shin %>%
  mutate(업종 = str_replace(업종, "기타요식", "요식/유흥")) %>%
  mutate(업종 = str_replace(업종, "일식/중식/양식", "요식/유흥")) %>%
  mutate(업종 = str_replace(업종, "한식", "요식/유흥")) %>%
  mutate(업종 = str_replace(업종, "제과/커피/패스트푸드", "요식/유흥")) %>%
  mutate(업종 = str_replace(업종, "유흥", "요식/유흥")) %>%
  mutate(업종 = str_replace(업종, "요식/요식/유흥", "요식/유흥")) %>%
  group_by(소비일자,업종,성별, 연령대) %>%
  summarize(소비건수 = sum(소비건수))
```

### 2. 데이터 분석
#### 2.1 카드 연령별 소비 데이터
```{r}
# 삼성카드 연령별 소비건수 평균
card_age <- card %>% 
  select(연령대,소비건수) %>%
  group_by(연령대) %>%
  summarize(소비건수평균 = mean(소비건수))

ggplot(data = card_age) +
  geom_col(aes(연령대,소비건수평균)) +
  ggtitle("삼성카드 연령별 소비 건수 평균") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")
```
```{r}
# 신한카드 연령별 소비건수 평균
shin_age <- shin %>%
  select(연령대,소비건수) %>%
  group_by(연령대) %>%
  summarize(소비건수평균 = mean(소비건수))

ggplot(data = shin_age) +
  geom_col(aes(연령대,소비건수평균)) + 
  ggtitle("신한카드 연령별 소비 건수 평균") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) +
  theme(legend.position = "top")
```

#### 2.2 카드 업종별 소비 데이터
```{r}
# 삼성카드 업종별 소비건수 평균 (상위 3개만 추출)
card_job <- card %>%
  select(업종,소비건수) %>%
  group_by(업종) %>%
  summarize(소비건수평균 = mean(소비건수))
card_job <- card_job[order(-card_job$소비건수평균),]
card_job <- card_job %>%
  head(5)

ggplot(data = card_job) +
  geom_col(aes(reorder(업종, -소비건수평균),소비건수평균)) + 
  ggtitle("삼성카드 업종별 소비 건수 평균") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")

```

```{r}
# 신한카드 업종별 소비건수 평균 (상위 3개만 추출) 
shin_job <- shin %>%
  select(업종,소비건수) %>%
  group_by(업종) %>%
  summarize(소비건수평균 = mean(소비건수))
shin_job <- shin_job[order(-shin_job$소비건수평균),]
shin_job <- shin_job %>%
  head(5)

ggplot(data = shin_job) +
  geom_col(aes(reorder(업종, -소비건수평균),소비건수평균)) + 
  ggtitle("신한카드 업종별 소비 건수 평균") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")

```

### 2.3 상위 3개 데이터 시각화
#### 2.3.1 편의점
```{r}
# 삼성카드 편의점 데이터
card2 <- card %>%
  filter(업종 == "편의점")

ggplot(data = card2) +
  geom_smooth(mapping = aes(x = 소비일자, y = 소비건수, color = 성별)) +
  facet_wrap(~연령대, nrow = 3) +
  ggtitle("연령별 편의점 소비(삼성카드)") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")
```
```{r}
# 신한카드 편의점 데이터
shin2 <- shin %>%
  filter(업종 == "편의점")

ggplot(data = shin2) +
  geom_smooth(mapping = aes(x = 소비일자, y = 소비건수, color = 성별)) +
  facet_wrap(~연령대, nrow = 3) +
  ggtitle("연령별 편의점 소비(신한카드)") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")
```

#### 2.3.2 요식/유흥
```{r}
# 삼성카드 요식/유흥 데이터
card3 <- card %>%
  filter(업종 == "요식/유흥")

ggplot(data = card3) +
  geom_smooth(mapping = aes(x = 소비일자, y = 소비건수, color = 성별)) +
  facet_wrap(~연령대, nrow = 3) + 
  ggtitle("연령별 요식/유흥 소비(삼성카드)") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")
```
```{r}
# 신한카드 요식/유흥 데이터
shin3 <- shin %>%
  filter(업종 == "요식/유흥")

ggplot(data = shin3) +
  geom_smooth(mapping = aes(x = 소비일자, y = 소비건수, color = 성별)) +
  facet_wrap(~연령대, nrow = 3) +
  ggtitle("연령별 요식/유흥 소비(신한카드)") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")
```

#### 2.3.3 할인점/마트(슈퍼마켓)
```{r}
# 삼성카드 할인점/마트 데이터
card4 <- card %>%
  filter(업종 == "할인점/마트")

ggplot(data = card4) +
  geom_smooth(mapping = aes(x = 소비일자, y = 소비건수, color = 성별)) +
  facet_wrap(~연령대, nrow = 3) +
  ggtitle("연령별 할인점/마트 소비(삼성카드)") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")
```
```{r}
# 신한카드 할인점/슈퍼마켓 데이터
shin4 <- shin %>%
  filter(업종 == "할인점/슈퍼마켓")

ggplot(data = shin4) +
  geom_smooth(mapping = aes(x = 소비일자, y = 소비건수, color = 성별)) +
  facet_wrap(~연령대, nrow = 3) +
  ggtitle("연령별 할인점/슈퍼마켓 소비(신한카드)") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")
```

### 3. 평택시 인구 데이터
#### 3.1 데이터 불러오기
```{r}
pop <- read_xlsx(path = "/home/kdx030/연령별인구현황.xlsx")
glimpse(pop)
```

#### 3.2 데이터 전처리
```{r}
# 필요없는 중복열 삭제
pop <- pop %>%
  select(-연령구간인구수...4, -연령구간인구수...17)

# 평택시 행정기관코드열 삭제
pop <- pop %>%
  select(-1)

# 카드 데이터상에는 20대부터 60대의 데이터까지 있다 이외 데이터 삭제

pop <- pop %>%
  select(-3, -4, -10,-11, -12, -13, -15, -16, -22, -23, -24, -25)

# 평택시 전체 인구 데이터 삭제
pop <- pop[-1,]

# 남성 여성 데이터 나누기
pop_f <- pop %>%
  select(1,8,9,10,11,12,13)

pop <- pop %>%
  select(-8,-9,-10,-11,-12,-13)

# 각 데이터 열 이름 바꾸기
names(pop)[2] <- c("성별")

for(i in 3:7){
  names(pop)[i] <- c((i-1)*10)
  
}

names(pop_f)[2] <- c("성별")
for(i in 3:7){
  names(pop_f)[i] <- c((i-1)*10)
  
}

# 데이터 합치기
pop <- rbind(pop,pop_f)


# 연령대 열로 통합하기
pop <- pop %>%
  gather('20','30','40','50','60', key = "연령대", value = "인구수")

# 인구수 열 데이터에서 , 제거하고 문자형 타입에서 정수형 타입으로 변환
pop$인구수 <- gsub(",","",pop$인구수)
pop$인구수 <- as.integer(pop$인구수)
```

#### 3.3 평택시 인구 데이터 시각화
```{r}
ggplot(data = pop) + 
  geom_col(mapping = aes(x = 연령대, y = 인구수,  fill = 성별),
           position = "dodge") +
  facet_wrap(~행정기관, nrow = 3) + 
  ggtitle("평택시 각 동별 연령 인구분포") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + 
  theme(legend.position = "top")
```